package eu.dariolucia.ccsds.cfdp.entity.request;

/**
 * The Report.request primitive shall be used to request a report on the status of a
 * transaction.
 *
 * Report.request is generated by any CFDP user at any time during the lifetime of any
 * transaction.
 *
 * Receipt of Report.request shall cause the CFDP entity to return a Report.indication
 * primitive to the CFDP user.
 *
 * Ref. CCSDS 727.0-B-5, 3.4.5
 */
public class ReportRequest implements ICfdpRequest {

    /**
     * The Transaction ID parameter shall uniquely identify a single instance of FDU
     * delivery and shall contain the ID of the source CFDP entity together with a sequence number
     * that is specific to that entity.
     *
     * At any moment, any given transaction ID is unique within the CFDP addressing
     * domain that encompasses the source CFDP entity.
     */
    private final long transactionId;

    /**
     * ReportRequest full constructor.
     *
     * @param transactionId the transaction ID that uniquely identify a single instance of FDU delivery
     */
    public ReportRequest(long transactionId) {
        this.transactionId = transactionId;
    }

    public long getTransactionId() {
        return transactionId;
    }

    @Override
    public String toString() {
        return "ReportRequest{" +
                "transactionId=" + transactionId +
                '}';
    }
}
