package eu.dariolucia.ccsds.cfdp.entity.request;

/**
 * The Resume.request primitive shall be used to request that a suspended transaction be
 * resumed.
 *
 * Resume.request is generated by any CFDP user at any time during the lifetime of any
 * transaction, except in the case of a transaction sent in unacknowledged mode, for which it
 * can only be generated by the transaction’s source user.
 *
 * Receipt of Resume.request shall have no effect on any transaction that is not currently
 * suspended. For a transaction that is currently suspended, it shall cause the local CFDP entity
 * to initiate Resume procedures.
 *
 * User application developers may find it advisable to provide automated support for one
 * special case of transaction resumption, which applies to any transaction the user application
 * can determine is currently suspended solely due to transaction inactivity (i.e., as a result of
 * an Inactivity fault). On receipt of any service indication produced because of arrival of a
 * PDU for such a transaction, the user application might infer that the transaction’s inactivity is
 * ended and thereupon automatically resume the transaction.
 *
 * Ref. CCSDS 727.0-B-5, 3.4.4
 */
public class ResumeRequest implements ICfdpRequest {

    /**
     * The Transaction ID parameter shall uniquely identify a single instance of FDU
     * delivery and shall contain the ID of the source CFDP entity together with a sequence number
     * that is specific to that entity.
     *
     * At any moment, any given transaction ID is unique within the CFDP addressing
     * domain that encompasses the source CFDP entity.
     */
    private final long transactionId;

    /**
     * ResumeRequest full constructor.
     *
     * @param transactionId the transaction ID that uniquely identify a single instance of FDU delivery
     */
    public ResumeRequest(long transactionId) {
        this.transactionId = transactionId;
    }

    public long getTransactionId() {
        return transactionId;
    }

    @Override
    public String toString() {
        return "ResumeRequest{" +
                "transactionId=" + transactionId +
                '}';
    }
}
